# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/telemetry
dlthub_telemetry = true

[destination.weaviate.module_config."text2vec-openai"]
model = "ada"
modelVersion = "002"
type = "text"
[destination.weaviate.module_config."generative-openai"]
model = "gpt-3.5-turbo"